[tool.poetry]
name = "bookk-bookk"
version = "0.1.0"
description = "required packages for bookk-bookk"
authors = ["kde6260 <kde6260@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "3.7.4"
async-timeout = "3.0.1"
attrs = "19.3.0"
chardet = "3.0.4"
click = "7.1.2"
fastapi = "0.68.0"
gunicorn = "20.0.4"
h11 = "0.9.0"
httptools = "0.1.1"
idna = "2.9"
multidict = "4.7.6"
notion = "0.0.25"
pydantic = "1.6.2"
python-dotenv = "0.13.0"
python-multipart = "0.0.5"
slackclient = "2.7.1"
starlette = "0.14.2"
uvicorn = "0.11.7"
uvloop = "0.14.0"
websockets = ">=8.0.0"
yarl = "1.4.2"

[tool.poetry.dev-dependencies]
appdirs = "1.4.4"
cfgv = "3.1.0"
distlib = "0.3.0"
filelock = "3.0.12"
identify = "1.4.19"
importlib-metadata = "1.6.1"
mypy = "0.780"
mypy-extensions = "0.4.3"
nodeenv = "1.4.0"
pre-commit = "2.5.0"
pytest = "5.4.3"
pytest-mock = "3.1.1"
PyYAML = "5.4.1"
six = "1.15.0"
toml = "0.10.1"
typed-ast = "1.4.1"
typing-extensions = "3.7.4.2"
virtualenv = "20.0.21"
zipp = "3.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
