version: 2

jobs:
  branches:
  build:
    working_directory: ~/bookk-bookk
    docker:
      - image: kde6260/bookk-ci:latest

    steps:
      - checkout

      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile --ignore DL3013 --ignore DL3025

      - run:
          name: Install Packages
          command: poetry install --no-root
      - run:
          name: Lint Python code
          command: poetry run flake8 --ignore E501 --max-complexity 10 --exclude ./venv

      - run:
          name: Type check with mypy
          command: poetry run mypy .

      - run:
          name: Execute Pytest
          command: poetry run pytest tests
